# defines the prefix of all created resources, including the namespace
fullnameOverride: gpu-driver

crd:
  # when false CustomResourceDefinitions will not be installed
  enabled: true

namespace:
  # when false the namespace will not be created and it must already exist
  create: true

# List of pre-existing secrets containing private registry credentials
# For example
# imagePullSecrets:
#   - name: myRegistryKeySecretName
imagePullSecrets: []

manager:
  # when false the manager deployment will not be installed
  enabled: true
  # defaults to europe-docker.pkg.dev
  repository: europe-docker.pkg.dev
  # defaults to kyma-project/prod/gpu-driver
  image: kyma-project/prod/gpu-driver
  # the gpu-driver container tag
  tag: 0.4.3

devicePlugin:
  repository: gcr.io
  image: gke-release/nvidia-gpu-device-plugin
  version: 1.0.25-gke.56

installer:
  repository: ghcr.io
  image: gardenlinux/gardenlinux/kmodbuild
